//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace filmtutkunu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicibilgileri
    {
        public int kullaniciid { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string kullaniciadi { get; set; }
        public string email { get; set; }
        public string şifre { get; set; }
        public string dogumtarihi { get; set; }
    }
}
